### ISSUE TITLE
GPLv3?

### ISSUE THREAD

**Issue by ghost** [Greedysky/TTKWidgetTools#10]
Qt itself is LGPLv3. You should know the different between LGPLv3 vs GPLv3. Having your library licensed with GPLv3 forced anyone to use your library to also release their code as GPLv3. This is what GPLv3 is all about. Who dared to use your library other than open source projects?

**Comment by ghost** [comment]
You can fix this by using linking exception with GPLv3:

https://en.wikipedia.org/wiki/GPL_linking_exception

**Comment by ghost** [comment]
@Greedysky

**Comment by uestc-alayi** [comment]
> Qt本身就是LGPLv3。你应该知道LGPLv3和GPLv3之间的区别。用 GPLv3 授权你的库会迫使任何人使用你的库来发布他们的代码作为 GPLv3。这就是 GPLv3 的全部意义所在。除了开源项目之外，谁敢使用您的库？

是的，一些组件挺实用的，比自己造轮子快，可惜是GPL不是LGPL

**Comment by Greedysky** [comment]
> > Qt本身就是LGPLv3。你应该知道LGPLv3和GPLv3之间的区别。用 GPLv3 授权你的库会迫使任何人使用你的库来发布他们的代码作为 GPLv3。这就是 GPLv3 的全部意义所在。除了开源项目之外，谁敢使用您的库？
> 
> 是的，一些组件挺实用的，比自己造轮子快，可惜是GPL不是LGPL

协议这块现在是商业不友好的，后期的话会考虑LGPL

**Comment by Greedysky** [comment]
Done
