### ISSUE TITLE
[Crash] Crash while using button

### ISSUE THREAD

**Issue by really-hzy** [Greedysky/TTKWidgetTools#11]
environment: win10 qtcreator10.1 qt5.15.2
compiler: microsoft visual c++ compiler 16.11.33214.272

![image](https://github.com/Greedysky/TTKWidgetTools/assets/22075489/462fbfcc-ec02-4665-83f9-4b624e36fcd2)

**Comment by Greedysky** [comment]
em.... just crashes on MSVC, MinGW is ok.

**Comment by really-hzy** [comment]
您好，您的邮件我已收到，会尽快给您回复

**Comment by Greedysky** [comment]
Fixed

**Comment by really-hzy** [comment]
您好，您的邮件我已收到，会尽快给您回复
