### ISSUE TITLE
有些小疑问希望能指点下

### ISSUE THREAD

**Issue by 17739396307** [Greedysky/TTKWidgetTools#6]
刚下载项目，使用ui设计师打开了ttktoolsapplication.ui文件，我发现QLabel里面放了其他控件，我想问下这里使用Qlabel不使用QWidget是有什么其他的目的吗？这个ui文件是自己写的不是设计师生成的吗？

**Comment by Greedysky** [comment]
看需求，ui文件可以自己修改
